language: cpp

compiler:
  - clang
  - gcc

before_install:
  - git clone http://github.com/redis/hiredis && cd hiredis && make && sudo make install && sudo ldconfig && cd ..

script:
  - mkdir build
  - cd build
  - cmake ..
